[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
localdao = "GQq7ZdCqWXLjNnNjjWJmgFNxNdomW34enX48owiP2WHP"
[programs.devnet]
localdao = "GQq7ZdCqWXLjNnNjjWJmgFNxNdomW34enX48owiP2WHP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
